image:
  name: hashicorp/terraform:0.11.13

stages:
  - validate

tffmt:
  stage: validate
  tags:
    - default
  script:
    - terraform fmt -write=false -diff -check

tfvalidate:
  stage: validate
  tags:
    - default
  script:
    - mv main.tf.ci main.tf
    - mv terraform.tfvars.ci terraform.tfvars
    - mkdir -p ~/.ssh/keys
    - touch ~/.ssh/keys/test_test.pem
    - terraform init
    - terraform validate
