variable "resource_group_name" {}
variable "env" {}
variable "az_region" {}
variable "ssh_key_pub" {}
variable "network_interface_id" {}
variable "primary_blob_endpoint" {}
variable "container_name" {}
variable "vm_size" {}
variable "client_name" {}
variable "private_ip" {}
variable "public_ip" {}
